test

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,24 +1,52 @@
-name: CI
-
-on: [push]
-
-
+name: Symfony with PostgreSQL
+on: [push, pull_request]
 jobs:
-  build-test:
+  symfony:
+    name: Symfony
     runs-on: ubuntu-latest
-
+    services:
+      postgres:
+        image: postgres:10.8
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+          POSTGRES_DB: postgres
+        ports:
+          - 5432/tcp
+        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
     steps:
-    - uses: shivammathur/setup-php@v2
-      with:
-        php-version: '7.4'
-        extensions: imagick
-        tools: composer, phpunit
-
-    - uses: actions/checkout@v1
-    - uses: php-actions/composer@v1
+      - name: Checkout
+        uses: actions/checkout@v2
       
-    - uses: php-actions/phpunit@v1
-      with:
-        config: ./phpunit.xml.dist
-        memory: 256M
-    
+      - name: Setup PHP, with composer and extensions
+        uses: shivammathur/setup-php@v2 #https://github.com/shivammathur/setup-php
+        with:
+          php-version: '7.4'
+          extensions: imagick, mbstring, xml, ctype, iconv, intl, pdo_sqlite, pgsql
+          coverage: xdebug #optional
+      
+      - name: Get composer cache directory
+        id: composercache
+        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
+      
+      - name: Cache composer dependencies
+        uses: actions/cache@v2
+        with:
+          path: ${{ steps.composercache.outputs.dir }}
+          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
+          restore-keys: ${{ runner.os }}-composer-
+      
+      - name: Install Composer dependencies
+        run: |
+          composer install --no-progress --prefer-dist --optimize-autoloader
+      
+      - name: Run Migration
+        run: |
+          composer require symfony/orm-pack
+          php bin/console doctrine:schema:update --force || echo "No migrations found or schema update failed"
+          php bin/console doctrine:migrations:migrate || echo "No migrations found or migration failed"
+        env:
+          DATABASE_URL: postgres://postgres:postgres@127.0.0.1:${{ job.services.postgres.ports[5432] }}/postgres?charset=UTF-8
+      
+      - name: Run Tests
+        run: php bin/phpunit --coverage-text
